### ISSUE TITLE
fatal  error C1083: Cannot open include file: 'unistd.h': No such file 

### ISSUE THREAD

**Issue by meiry** [Revan600/LiteNetLibPP#1]
Build started...
1>------ Build started: Project: lnl, Configuration: Debug x64 ------
1>main.cpp
1>C:\dev\my\rudp_imp\LiteNetLibPP-main\src\main.cpp(2,10): fatal  error C1083: Cannot open include file: 'unistd.h': No such file or directory
1>Done building project "lnl.vcxproj" -- FAILED.
2>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
========== Build: 1 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

Using : 
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.3.3

c++17

**Comment by Revan600** [comment]
Should be fixed in https://github.com/Revan600/LiteNetLibPP/commit/d6c82214fa371eaa5137c55cf700ee9332cb422c
